### ISSUE TITLE
Nice theme, please continue with it

### ISSUE THREAD

**Issue by DutchPete** [kinmury/obsidian-ukiyo#1]
This is shaping up to be a nice theme, you should really try to complete it. Well ……… what is complete, it never is, I guess, but you know what I mean.

I think I might like the dark version even better than the light one, that's personal, of course.
Well done so far! Keep up the good work.

**Comment by kinmury** [comment]
Thank You, I'm glad that you like the theme (I assume you also saw the *Alternative Themes*, using the Style Settings). I will keep developing the theme whenever it's need or someone notifies me an issue that needs to be fixed or requests me a new feature.

Since this isn't and issue, I'll proceed to close it. Once again, I'm glad that you like it and I hope it suits your needs. :smile:

**Comment by C-r-y-p-t-i-d** [comment]
Just wanted to add, I really appreciate your work @kinmury , and the Ukiyo default theme has become my new daily theme. Keep up the good work! Best wishes.
