### ISSUE TITLE
Improve UI aesthetic/readability

### ISSUE THREAD

**Issue by wangb08** [kinmury/obsidian-ukiyo#2]
Hi guys.

I has updated the latest version before, but the UI experience of the latest version is very bad. So I had to roll back to the previous version. 
Specifically, the latest version of UI layout is too complicated for comfort. If possible, I suggest further simplifying the theme and optimizing the color scheme, but not hiding the icon or adding a bit of messy lines and boxes.

**Comment by kinmury** [comment]
Hello there :D

By implying the `UI` I understand that everything you see makes the use of Obsidian difficult or more complicated that it should. There are a lot of things that could be "wrong" and make said experience "bad".

The one thing that I know its a big change would be the side panels. If you use the default theme or any other theme, the side panels are fixed to the workspace, making said workspace change its size and content whenever any of the side panels appears on screen.

I personally find that a little odd, since I don't think the hole note should be transform and resize whenever a side panel is opened, so instead I make said panels to appear above the note (or notes) that is being used. Basically everything is the same, but the side panels wont resize the opened note (or notes).

By default the opacity of said panels is lowered, so that you can see the content of the note in case you aren't using/hovering over the panel itself. Once you put your mouse over the panel, the opacity will restore to its original value, so that you can use the panel with ease.

Either way, I understand that not everyone will like said change, so I plan to create a **Style Settings** *Setting* to let anyone change the explained behaviour to his liking.

Moving to the theme structure and color scheme, I know that I'm not the best at creating a color palette/color scheme, so I can see why some people would see that the chosen colors aren't the best suited. I also plan to add more setting where you can choose the color you want for elements like bold, italic, links, image borders, among other small thing like this.

But I have a few questions that I like for you to answer, since I don't understand your point:
- **What do you mean by "simplifying"?** - For what I understand (and what I've actually done) is to remove unnecessary elements of the `UI`, so that you don't need to be bother by elements that you don't use on a daily basis.

By default, I hide most of the things, but by hovering over them they reaper on your screen. I even have a setting calle *Global UI*, on **Hide User Interface**, which lets you hide even more things (but it uses the same logic as the deafult setting, where you can hover over the place the `UI` should appear and it will reveal it self). But I assume you knew that, so I ask you to further elaborate about the "simplifying" idea.

- **What do you mean by "hiding the icon or adding a bit of messy lines and boxes"?** - I hide a lot of stuff, not just icons, so you should be more specific about it. Also I don't know that "messy lines" or "boxes" I "have added". Could you please elaborate?

If its possible, could you attach screenshots about the things you find "confusing" or want to be "simplified" so that I'm on the same page as you? That would help me a lot.

And one last thing, there is a new *Default Theme* that is on the making and, when its released, there will be a lot of things on my theme that will break and I have to fix. So beware that any feature or fix won't be implemented until said theme is released and my base theme is fixed. I will use said period of time to fix and improve the theme, so I'm glad for your input :D

**Comment by kinmury** [comment]
There always be something to hide, but I personally don't want to go too far (even though I hide most of the `UI` to be fair). About the outline vertical line, in a previous theme someone pointed me to add it, so that's why it's there (and, in my opinion, it lets me see things in a more structured way).

But I'll make sure to add a setting where you can disable or enabled said vertical lines. (I assume that you also don't like the vertical lines that appear on the folders/files structure on the right panel as well).

And about the toolbars, they are hidden permanently unless you hover over them. The same way you need to hover over the sides to make said toolbars appear when the side panels are closed, you need to do the same when said panels are opened.

Either way, I plan to add a setting where you can choose to make the toolbar appear when the panel is opened or only to appear when you hover over it.

All issues, suggestions and features request are welcome and, even though I create and design the theme to my liking, I'll always have into account said suggestions, since it's now not only my personal theme but also other people theme.

Once again, said changes won't be active until the new default theme is released to the public. I hope that the previous version will suffice you in the mean time.

Thank you for your patience :D

**Comment by yarub123** [comment]
@kinmury  Had no other way of contacting you a few months ago. But wanted to let you know this is absolutely and probably will remain my favorite theme thus far. I love you and thank you, sincerely. Amazing work you've done here ♥️. Only thing I did was turn off the font you had on. I found it unreadable and very cluttered, even though at first I thought it was fine and actually liked it. But that was my only honest thing about it. Other than that, seriously amazing, especially with that new update 😍

**Comment by kinmury** [comment]
Hi @yarub123 😄, I'm really glad that you like and enjoy my theme 😊

I'm currently working on the update of the theme to match everything to the new Obsidan v1.0.0 version, so I'm sorry for all the broken things that you may see when using the current theme. And yes, I do agree that the previous font was cluttered, that's why I had changed it to a new one 😋.

I'm trying my best to make the updated come out as soon as possible by changing just all the basic things first and, later on, adding all the interesting stuff little by little, since some stuff are just straight up broken.

Thank you for your patience and, once again, I'm glad you like it 😊

And just a quick FYI, I don't mind if you even create a new issue just to say anything to me, but you can also find me easily on the _Obsidian Discord Server_ just by `@me` at any time (most of my free time I spend on that server, so you can find me there as well)

**Comment by kinmury** [comment]
I finally have finished reworking the theme. For what I'm seeing, this issue shouldn't be a problem anymore. In case there is someting that must be fixed, please open a new issue and specify what's the problem and I'll fix it 😁
