### ISSUE TITLE
Changing Colour Scheme

### ISSUE THREAD

**Issue by LisaRooij** [kinmury/obsidian-ukiyo#6]
Hi! 

I am an absolute imbecile who does not know how to code but love the theme. How do I access the different colour schemes (e.g. Academy)?

Thanks!

**Comment by kinmury** [comment]
I'm glad that you like the theme 😊

You don't need to know how to code in order to change the colour scheme. You need to install a plugin named **Style Settings** located on the Community Plugins. Once you have downloaded said plugin and enabled it on the community plugins section of your vault settings, you will see that there is a new settings section called "Style Settings".

Once you enter said section, you'll see al the settings that this theme provides, being the first one *General Settings*. Inside you'll find the "Color Scheme" setting that you need in order to select one.

This plugin works for all the themes that provides said settings, which means not all themes provide style settings.

I'll leave this issue opened for now. If you succeded you can close this issue (or I will close it after a while) or keep asking me questions relating this issue.

**Comment by LisaRooij** [comment]
> I'm glad that you like the theme 😊
> 
> You don't need to know how to code in order to change the colour scheme. You need to install a plugin named **Style Settings** located on the Community Plugins. Once you have downloaded said plugin and enabled it on the community plugins section of your vault settings, you will see that there is a new settings section called "Style Settings".
> 
> Once you enter said section, you'll see al the settings that this theme provides, being the first one _General Settings_. Inside you'll find the "Color Scheme" setting that you need in order to select one.
> 
> This plugin works for all the themes that provides said settings, which means not all themes provide style settings.
> 
> I'll leave this issue opened for now. If you succeded you can close this issue (or I will close it after a while) or keep asking me questions relating this issue.

Many thanks! This does indeed work. Except I have noticed that when I change it only _Golden Coffee_ changes the colour scheme, anything I can do to fix that?

**Comment by kinmury** [comment]
Thats odd, it works on my end. Try to restard Obsidian and check if you have the last version of the theme (and of Obsidian, just in case). I just checked it work on a new vault, so I'm not sure why it doesn't work on your end.

**Comment by LisaRooij** [comment]
It certainly is odd! 

I've checked and both the app and the theme are up-to-date, and have done 2 firm restarts of the programme. Should I try to restart the whole PC or do you have other suggestions? :)

**Comment by kinmury** [comment]
Try to create a new vault, install only the theme and the plugin. If that doesn't work try to re-install the theme.

**Comment by LisaRooij** [comment]
I think I've cracked the code! 

The themes will work but only using Dark Mode! Thanks!

**Comment by kinmury** [comment]
Oh yeah, I forgot about that detail since my main mode is Dark. Sorry about that 😅
I'll close the issue now. If there is anything wrong or you think there is something that can be improved or added to the theme, don't hesiate to create a new issue.
Enjoy the theme 😊
